import React from 'react';
import { Box, Text } from '@chakra-ui/react';

const PrivacyPolicy = () => {
  return (
    <Box p={8}>
      <Text fontSize="4xl" fontWeight="bold" mb={4}>
        Privacy Policy
      </Text>

      <Text mb={4}>
        Last updated: 06 April 2024
      </Text>

      <Text mb={4}>
        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </Text>

      <Text mb={4}>
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
      </Text>

      <Text fontWeight="bold" mt={6} mb={2}>
        Interpretation and Definitions
      </Text>

      <Text fontWeight="bold" mb={2}>
        Interpretation
      </Text>

      <Text mb={4}>
        The words in which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.
      </Text>

      <Text fontWeight="bold" mt={6} mb={2}>
        Definitions
      </Text>

      <Text mb={4}>
        For the purposes of this Privacy Policy:
      </Text>

      <Box as="ul" pl={6} mb={4}>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Account</Text> means a unique account created for You to access our Service or parts of our Service.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Company</Text> (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Guru iPhone.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Cookies</Text> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Country</Text> refers to India.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Device</Text> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Personal Data</Text> is any information that relates to an identified or identifiable individual.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Service</Text> refers to the Website.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Service Provider</Text> means any natural or legal person who processes the data on behalf of the Company.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Third-party Social Media Service</Text> refers to any website or any social network website through which a User can log in or create an account to use the Service.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Usage Data</Text> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">Website</Text> refers to Guru iPhone, accessible from <Text as="span" fontStyle="italic">gurusiphone.com</Text>.
        </Box>
        <Box as="li" mb={2}>
          <Text fontWeight="bold">You</Text> means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
        </Box>
      </Box>

      <Text fontWeight="bold" mt={6} mb={2}>
        Collecting and Using Your Personal Data
      </Text>

      <Text fontWeight="bold" mb={2}>
        Types of Data Collected
      </Text>

      <Text mb={4}>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </Text>

      <Box as="ul" pl={6} mb={4}>
        <Box as="li" mb={2}>Email address</Box>
        <Box as="li" mb={2}>First name and last name</Box>
        <Box as="li" mb={2}>Phone number</Box>
        <Box as="li" mb={2}>Address, State, Province, ZIP/Postal code, City</Box>
        <Box as="li" mb={2}>Usage Data</Box>
      </Box>

      <Text fontWeight="bold" mt={6} mb={2}>
        Contact Us
      </Text>

      <Text mb={4}>
        If you have any questions about this Privacy Policy, You can contact us:
      </Text>

      <Text>Email: <Text as="span" fontWeight="bold">guruIphone@gmail.com</Text></Text>
    </Box>
  );
};

export default PrivacyPolicy;
